imports:
    -  { resource: 'parameters/services_url_directory/index.yml' }
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: '%services.autowire%'      # Automatically injects dependencies in your services.
        autoconfigure: '%services.autoconfigure%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '%app_services.src_resource%'
        exclude:
            - '%app_services.exclude.d_i%'
            - '%app_services.exclude.entity%'
            - '%app_services.exclude.kernel%'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '%app_services.controller_resource%'
        tags: ['%app_services.controller_tags%']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
